import {defineField, defineType} from 'sanity'

export const campaignType = defineType({
  name: 'campaign',
  title: 'Campaign page',
  type: 'document',
  groups: [
    {name: 'seo', title: 'SEO'},
    {name: 'hero', title: 'Hero'},
    {name: 'intro', title: 'Intro'},
    {name: 'stays', title: 'Stays'},
    {name: 'experiences', title: 'Experiences'},
    {name: 'itinerary', title: 'Itinerary'},
    {name: 'passport', title: 'Passport'},
    {name: 'offers', title: 'Offers'},
    {name: 'closing', title: 'Closing'},
  ],
  fields: [
    defineField({
      name: 'promoCode',
      title: 'Promo code',
      type: 'string',
      group: 'hero',
      initialValue: 'CHECKINTONELSON',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'accentColor',
      title: 'Hero accent color',
      type: 'string',
      group: 'hero',
      description: 'Used on Nelson. and Experience More.',
      initialValue: '#8fc86a',
    }),

    defineField({
      name: 'seoTitle',
      title: 'Browser title',
      type: 'string',
      group: 'seo',
    }),
    defineField({
      name: 'seoDescription',
      title: 'Meta description',
      type: 'text',
      rows: 3,
      group: 'seo',
    }),
    defineField({
      name: 'canonicalUrl',
      title: 'Canonical URL',
      type: 'url',
      group: 'seo',
    }),

    defineField({
      name: 'heroPhrase1Line1',
      title: 'Headline A · line 1',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroPhrase1Line2',
      title: 'Headline A · line 2 (accent)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroPhrase2Line1',
      title: 'Headline B · line 1',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroPhrase2Line2',
      title: 'Headline B · line 2 (accent)',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroLede',
      title: 'Hero lede',
      type: 'text',
      rows: 4,
      group: 'hero',
    }),
    defineField({
      name: 'heroPrimaryCta',
      title: 'Hero primary button',
      type: 'cta',
      group: 'hero',
    }),
    defineField({
      name: 'heroSecondaryCta',
      title: 'Hero secondary button',
      type: 'cta',
      group: 'hero',
    }),
    defineField({
      name: 'heroPromoLabel',
      title: 'Promo card label',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroPromoTitle',
      title: 'Promo card title',
      type: 'string',
      group: 'hero',
      description: 'Use {code} where the promo code should appear.',
    }),
    defineField({
      name: 'heroPromoCopy',
      title: 'Promo card copy',
      type: 'text',
      rows: 3,
      group: 'hero',
    }),
    defineField({
      name: 'heroSlides',
      title: 'Hero slides',
      type: 'array',
      of: [{type: 'heroSlide'}],
      group: 'hero',
    }),

    defineField({
      name: 'partnersStripLabel',
      title: 'Partner strip label',
      type: 'string',
      group: 'experiences',
    }),

    defineField({
      name: 'introEyebrow',
      title: 'Intro eyebrow',
      type: 'string',
      group: 'intro',
    }),
    defineField({
      name: 'introTitle',
      title: 'Intro title',
      type: 'string',
      group: 'intro',
    }),
    defineField({
      name: 'introCopy',
      title: 'Intro copy',
      type: 'text',
      rows: 5,
      group: 'intro',
    }),
    defineField({
      name: 'introAside',
      title: 'Intro aside',
      type: 'text',
      rows: 3,
      group: 'intro',
    }),

    defineField({
      name: 'staysEyebrow',
      title: 'Stays eyebrow',
      type: 'string',
      group: 'stays',
    }),
    defineField({
      name: 'staysTitle',
      title: 'Stays title',
      type: 'string',
      group: 'stays',
    }),
    defineField({
      name: 'staysCopy',
      title: 'Stays copy',
      type: 'text',
      rows: 3,
      group: 'stays',
    }),
    defineField({
      name: 'stays',
      title: 'Stays',
      type: 'array',
      of: [{type: 'stay'}],
      group: 'stays',
    }),

    defineField({
      name: 'experienceEyebrow',
      title: 'Experiences eyebrow',
      type: 'string',
      group: 'experiences',
    }),
    defineField({
      name: 'experienceTitle',
      title: 'Experiences title',
      type: 'string',
      group: 'experiences',
    }),
    defineField({
      name: 'experienceCopy',
      title: 'Experiences copy',
      type: 'text',
      rows: 3,
      group: 'experiences',
    }),
    defineField({
      name: 'partners',
      title: 'Experience partners',
      type: 'array',
      of: [{type: 'partner'}],
      group: 'experiences',
    }),

    defineField({
      name: 'itineraryEyebrow',
      title: 'Itinerary eyebrow',
      type: 'string',
      group: 'itinerary',
    }),
    defineField({
      name: 'itineraryTitle',
      title: 'Itinerary title',
      type: 'string',
      group: 'itinerary',
    }),
    defineField({
      name: 'itineraryCopy',
      title: 'Itinerary copy',
      type: 'text',
      rows: 3,
      group: 'itinerary',
    }),

    defineField({
      name: 'passportEyebrow',
      title: 'Passport eyebrow',
      type: 'string',
      group: 'passport',
    }),
    defineField({
      name: 'passportTitle',
      title: 'Passport title',
      type: 'string',
      group: 'passport',
    }),
    defineField({
      name: 'passportCopy',
      title: 'Passport copy',
      type: 'text',
      rows: 4,
      group: 'passport',
    }),
    defineField({
      name: 'passportUrl',
      title: 'LoyalBrew passport URL',
      type: 'url',
      group: 'passport',
    }),
    defineField({
      name: 'passportPrimaryCta',
      title: 'Passport button',
      type: 'cta',
      group: 'passport',
    }),
    defineField({
      name: 'passportSecondaryCta',
      title: 'Passport secondary button',
      type: 'cta',
      group: 'passport',
    }),
    defineField({
      name: 'passportNote',
      title: 'Passport note',
      type: 'text',
      rows: 3,
      group: 'passport',
    }),
    defineField({
      name: 'passportSteps',
      title: 'Passport steps',
      type: 'array',
      of: [{type: 'passportStep'}],
      group: 'passport',
    }),

    defineField({
      name: 'offersEyebrow',
      title: 'Offers eyebrow',
      type: 'string',
      group: 'offers',
    }),
    defineField({
      name: 'offersTitle',
      title: 'Offers title',
      type: 'string',
      group: 'offers',
      description: 'Use {code} where the promo code should appear.',
    }),
    defineField({
      name: 'offersCopy',
      title: 'Offers copy',
      type: 'text',
      rows: 3,
      group: 'offers',
    }),
    defineField({
      name: 'offerPerks',
      title: 'Offer bullets',
      type: 'array',
      of: [{type: 'string'}],
      group: 'offers',
    }),
    defineField({
      name: 'offersFinePrint',
      title: 'Offers fine print',
      type: 'string',
      group: 'offers',
    }),

    defineField({
      name: 'closingEyebrow',
      title: 'Closing eyebrow',
      type: 'string',
      group: 'closing',
    }),
    defineField({
      name: 'closingTitle',
      title: 'Closing title',
      type: 'string',
      group: 'closing',
    }),
    defineField({
      name: 'closingCopy',
      title: 'Closing copy',
      type: 'text',
      rows: 4,
      group: 'closing',
    }),
    defineField({
      name: 'closingPrimaryCta',
      title: 'Closing primary button',
      type: 'cta',
      group: 'closing',
    }),
    defineField({
      name: 'closingSecondaryCta',
      title: 'Closing secondary button',
      type: 'cta',
      group: 'closing',
    }),
    defineField({
      name: 'footerTitle',
      title: 'Footer title',
      type: 'string',
      group: 'closing',
    }),
    defineField({
      name: 'footerCopy',
      title: 'Footer copy',
      type: 'text',
      rows: 3,
      group: 'closing',
    }),
    defineField({
      name: 'footerPromoNote',
      title: 'Footer promo note',
      type: 'string',
      group: 'closing',
    }),
  ],
  preview: {
    select: {title: 'heroPhrase1Line1', subtitle: 'promoCode'},
    prepare({title, subtitle}) {
      return {
        title: title || 'Check Into Nelson',
        subtitle: subtitle || 'Campaign page',
      }
    },
  },
})
